"""In-app Notification ORM model.

Notifications are generated by system events (deadline warnings, report status
changes, approval requests) and surfaced to authenticated users via the
notifications API.

All notifications are tenant-scoped and user-specific. The frontend polls
/api/v1/notifications/unread-count for badge display, and lists notifications
on the notification panel.

Notification lifecycle:
- Created by system events (Celery tasks, service layer hooks)
- Read by the recipient via GET /api/v1/notifications
- Marked as read via POST /api/v1/notifications/mark-read
- is_read + read_at track acknowledgement for UX state management
"""
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from src.models.base import TenantAwareModel


class NotificationType(StrEnum):
    """Categories of in-app notifications.

    DEADLINE_WARNING:    Upcoming statutory reporting deadline (7/3/1 days before)
    DEADLINE_OVERDUE:    Statutory reporting deadline passed without submission
    REPORT_STATUS_CHANGE: Report transitioned to a new approval state
    APPROVAL_REQUIRED:  A report is awaiting action from the recipient
    """

    DEADLINE_WARNING = "deadline_warning"
    DEADLINE_OVERDUE = "deadline_overdue"
    REPORT_STATUS_CHANGE = "report_status_change"
    APPROVAL_REQUIRED = "approval_required"


class Notification(TenantAwareModel):
    """In-app notification record for a specific user.

    Created by system events (Celery deadline monitor, report status transitions)
    and surfaced to the user via the /api/v1/notifications endpoint.

    is_read + read_at track when the user acknowledged the notification.
    link provides a deep-link URL for the frontend to navigate directly to
    the relevant report or action item.
    """

    __tablename__ = "notifications"

    user_id: Mapped[UUID] = mapped_column(
        ForeignKey("users.id"),
        nullable=False,
        index=True,
        comment="FK to the user who should receive this notification",
    )
    type: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        comment="Notification category: deadline_warning, report_status_change, etc.",
    )
    title: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
        comment="Short notification title displayed in the notification list",
    )
    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Full notification body text",
    )
    link: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
        comment="Frontend deep-link URL for navigating to the relevant resource",
    )
    is_read: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
        comment="True = user has acknowledged this notification",
    )
    read_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when the user marked this notification as read",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<Notification user={self.user_id} type={self.type} "
            f"read={self.is_read}>"
        )
